[project]
name = "data-science-project-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "scikit-learn>=1.5.0",
    "sentence-transformers>=5.2.0",
]
